#cloud-config

package_update: true

package_upgrade: true

packages:
 - ca-certificates
 - curl
 - gnupg
 - lsb-release
 - git
 
runcmd:
  - sudo mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  - sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - git clone https://github.com/WhatsApp/proxy.git $HOME/whatsapp-proxy
  - docker compose -f $HOME/whatsapp-proxy/proxy/ops/docker-compose.yml up -d

